CREATE TABLE `organization_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orgName` varchar(255) NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`planType` enum('starter_saas','institution_pro','enterprise_pharma','featured_sponsor') NOT NULL,
	`estimatedTrialsPerYear` int NOT NULL DEFAULT 3,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `organization_inquiries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `participant_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`profileKey` varchar(64) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`age` int NOT NULL,
	`gender` enum('female','male','non_binary','prefer_not_to_say') NOT NULL,
	`educationLevel` enum('high_school_or_less','some_college','bachelors','graduate_degree') NOT NULL DEFAULT 'bachelors',
	`livingEnvironment` enum('urban','suburban','rural') NOT NULL DEFAULT 'suburban',
	`city` varchar(128) NOT NULL,
	`state` varchar(64) NOT NULL,
	`zipCode` varchar(20),
	`travelDistanceMiles` int NOT NULL DEFAULT 25,
	`isHealthyVolunteer` boolean NOT NULL DEFAULT true,
	`conditions` json NOT NULL DEFAULT ('[]'),
	`medications` json NOT NULL DEFAULT ('[]'),
	`hasRecentAntibiotics` boolean NOT NULL DEFAULT false,
	`smokerStatus` enum('never','former','current') NOT NULL DEFAULT 'never',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `participant_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `participant_profiles_profileKey_unique` UNIQUE(`profileKey`)
);
--> statement-breakpoint
CREATE TABLE `screener_questions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studyId` int NOT NULL,
	`orderIndex` int NOT NULL,
	`questionText` text NOT NULL,
	`explanation` text,
	`questionType` enum('yes_no','multiple_choice','single_choice','number') NOT NULL,
	`options` json DEFAULT ('[]'),
	`expectedAnswer` varchar(255) NOT NULL,
	`isDisqualifying` boolean NOT NULL DEFAULT true,
	`disqualificationReason` text,
	CONSTRAINT `screener_questions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `studies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`title` varchar(255) NOT NULL,
	`sponsorName` varchar(255) NOT NULL,
	`sponsorType` enum('university','hospital','biotech','pharma','research_center') NOT NULL,
	`piName` varchar(255) NOT NULL,
	`piTitle` varchar(255),
	`studyType` enum('clinical_trial','blood_draw','observational_survey','imaging_mri','cognitive_assessment') NOT NULL,
	`compensationAmount` int NOT NULL,
	`compensationType` varchar(64) NOT NULL DEFAULT 'Direct Payment (Stipend)',
	`compensationSchedule` text,
	`timeCommitment` varchar(128) NOT NULL,
	`durationWeeks` int DEFAULT 1,
	`locationType` enum('in_person','remote','hybrid') NOT NULL,
	`city` varchar(128) NOT NULL,
	`state` varchar(64) NOT NULL,
	`facilityAddress` text,
	`summary` text NOT NULL,
	`fullDescription` text NOT NULL,
	`irbApprovalNumber` varchar(64) NOT NULL DEFAULT 'IRB-2026-0894',
	`targetEnrollment` int NOT NULL DEFAULT 50,
	`currentEnrolled` int NOT NULL DEFAULT 0,
	`minAge` int NOT NULL DEFAULT 18,
	`maxAge` int NOT NULL DEFAULT 85,
	`targetGender` enum('all','male','female') NOT NULL DEFAULT 'all',
	`healthyVolunteersAccepted` boolean NOT NULL DEFAULT true,
	`requiredConditions` json NOT NULL DEFAULT ('[]'),
	`excludedConditions` json NOT NULL DEFAULT ('[]'),
	`targetDemographicFocus` varchar(255),
	`isFeatured` boolean NOT NULL DEFAULT false,
	`isSponsored` boolean NOT NULL DEFAULT false,
	`status` enum('recruiting','waitlist','closed') NOT NULL DEFAULT 'recruiting',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `studies_id` PRIMARY KEY(`id`),
	CONSTRAINT `studies_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `study_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studyId` int NOT NULL,
	`profileId` int NOT NULL,
	`status` enum('screener_passed','screened_out','pending_contact','scheduled','enrolled','completed','withdrawn') NOT NULL DEFAULT 'screener_passed',
	`screenerResponses` json NOT NULL,
	`qualificationScore` int NOT NULL DEFAULT 100,
	`disqualificationNotes` text,
	`researcherNotes` text,
	`appointmentDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `study_applications_id` PRIMARY KEY(`id`)
);
