import { Study, ScreenerQuestion } from "../drizzle/schema";

export const DEMO_STUDIES: Study[] = [
  {
    id: 1,
    slug: "healthy-aging-sensory-resilience-study",
    title: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    sponsorName: "Triangle Aging & Brain Sciences Center",
    sponsorType: "university",
    piName: "Dr. H. Whitman, MD",
    piTitle: "Professor of Medicine & Director, Triangle Center for Aging",
    studyType: "cognitive_assessment",
    compensationAmount: 650,
    compensationType: "Direct Deposit / Visa Gift Card",
    compensationSchedule: "$150 per visit (3 visits) + $200 completion bonus upon exit interview",
    timeCommitment: "3 visits over 6 weeks (1.5 hrs/visit)",
    durationWeeks: 6,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Triangle Clinical Research Pavilion, Durham, NC 27710",
    summary: "Investigating how combined visual and hearing cues affect cognitive resilience in older adults. Seeking healthy volunteers, especially men and rural participants.",
    fullDescription: "Our goal is to understand how the brain adapts to subtle sensory variations as we grow older. Participants undergo safe, non-invasive sensory tests and brief memory problem-solving activities on a tablet. You are compensated for each visit attended with full travel mileage reimbursements.",
    irbApprovalNumber: "Pro00109482",
    targetEnrollment: 120,
    currentEnrolled: 54,
    minAge: 50,
    maxAge: 85,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Severe Dementia", "Active Stroke within 6 months"],
    targetDemographicFocus: "Actively seeking rural residents, non-college educated volunteers, and men to achieve representative 40% male enrollment target.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 2,
    slug: "healthy-volunteer-immunology-blood-profile",
    title: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    sponsorName: "Triangle Thoracic & Surgical Immunology Lab",
    sponsorType: "hospital",
    piName: "Dr. Rachel Aris, MD, PhD",
    piTitle: "Chief of Cellular Immunology",
    studyType: "blood_draw",
    compensationAmount: 250,
    compensationType: "Direct Bank Deposit",
    compensationSchedule: "$100 for Visit 1 + $150 for Visit 2 (completed within 14 days)",
    timeCommitment: "2 visits (45 mins each, 2 weeks apart)",
    durationWeeks: 2,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Hospital South Clinics, Phlebotomy Core 3B, Durham, NC 27705",
    summary: "Routine fasting blood draws two weeks apart to establish baseline lymphocyte reference data for surgical organ transplant science.",
    fullDescription: "Healthy volunteers provide approximately 35ml of venous blood across two scheduled mornings. Blood samples help researchers measure natural lymphocyte population fluctuations to build control datasets for heart and kidney transplant rejection monitors.",
    irbApprovalNumber: "IRB-2026-00412",
    targetEnrollment: 60,
    currentEnrolled: 38,
    minAge: 18,
    maxAge: 70,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Active Chronic Infection", "Immunosuppressant Medication", "Bleeding Disorder"],
    targetDemographicFocus: "Reliable healthy volunteers who can commit to two punctually scheduled morning appointments.",
    isFeatured: true,
    isSponsored: false,
    status: "recruiting",
    createdAt: new Date("2026-08-05"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 3,
    slug: "remote-sleep-cardiac-rhythm-digital-study",
    title: "National Digital Sleep & Circadian Rhythm Observational Study",
    sponsorName: "BioVanguard Digital Health Institute",
    sponsorType: "biotech",
    piName: "Dr. Elena Rostova, PhD",
    piTitle: "Head of Computational Chronobiology",
    studyType: "observational_survey",
    compensationAmount: 320,
    compensationType: "Amazon E-Gift Card or Venmo",
    compensationSchedule: "$80 every 2 weeks + smart ring provided free to keep upon completion",
    timeCommitment: "10 minutes daily app check-in + sleep ring wear for 6 weeks",
    durationWeeks: 6,
    locationType: "remote",
    city: "Nationwide (Remote)",
    state: "US",
    facilityAddress: "Fully remote. Devices mailed directly to your home.",
    summary: "Participate entirely from home! Receive a complimentary medical-grade smart health ring, track your sleep cycles, and log daily energy ratings via our participant mobile app.",
    fullDescription: "Explore how daily screen exposure, ambient light, and stress affect sleep micro-architecture. You will wear an unobtrusive finger sensor while sleeping and fill out a quick 2-minute morning log. No clinic visits or blood draws required. Open to adults across all 50 states.",
    irbApprovalNumber: "WIRB-2026-9921",
    targetEnrollment: 400,
    currentEnrolled: 285,
    minAge: 18,
    maxAge: 75,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Shift Work Sleep Disorder", "Untreated Severe Sleep Apnea"],
    targetDemographicFocus: "Everyday working adults, parents, and students looking for low-friction remote compensation.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-10"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 4,
    slug: "oral-glp1-cardiometabolic-phase2",
    title: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist for Metabolic Health",
    sponsorName: "AstraApex Therapeutics & Triangle Endocrine Core",
    sponsorType: "pharma",
    piName: "Dr. Marcus Vance, MD",
    piTitle: "Principal Investigator & Chair of Metabolic Endocrinology",
    studyType: "clinical_trial",
    compensationAmount: 1850,
    compensationType: "Prepaid ClinCard / Direct Deposit",
    compensationSchedule: "$250 after screening/baseline + $200 per monthly follow-up + $450 final visit",
    timeCommitment: "8 clinic visits over 24 weeks + weekly home capsule regimen",
    durationWeeks: 24,
    locationType: "in_person",
    city: "Raleigh",
    state: "NC",
    facilityAddress: "AstraApex Phase II Clinical Trials Unit, Raleigh, NC 27607",
    summary: "Evaluating the efficacy and gastrointestinal tolerability of a novel once-weekly oral capsule formulation in individuals with elevated HbA1c or Type 2 Diabetes.",
    fullDescription: "Currently available GLP-1 therapies frequently require subcutaneous injections. This study evaluates an advanced once-weekly oral enteric capsule designed to improve metabolic glycemic control and weight parameters without injections. All medication, physician visits, and metabolic labs provided at no cost.",
    irbApprovalNumber: "IND-159483-IRB",
    targetEnrollment: 90,
    currentEnrolled: 47,
    minAge: 25,
    maxAge: 72,
    targetGender: "all",
    healthyVolunteersAccepted: false,
    requiredConditions: ["Type 2 Diabetes", "Prediabetes", "Metabolic Syndrome"],
    excludedConditions: ["Type 1 Diabetes", "History of Pancreatitis", "Thyroid C-Cell Carcinoma"],
    targetDemographicFocus: "Participants with diagnosed Type 2 Diabetes seeking novel oral therapeutic options.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-15"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 5,
    slug: "mri-functional-connectome-memory-mapping",
    title: "fMRI Functional Connectome & Working Memory Precision Mapping",
    sponsorName: "Carolina Institute for Advanced Neuroimaging",
    sponsorType: "research_center",
    piName: "Dr. Sophia Sterling, PhD",
    piTitle: "Associate Professor of Radiology and Biomedical Imaging",
    studyType: "imaging_mri",
    compensationAmount: 400,
    compensationType: "Direct Bank Transfer or Visa Debit",
    compensationSchedule: "$400 lump sum upon completion of the 2.5-hour imaging session",
    timeCommitment: "Single 2.5-hour session (1 hour in 3T MRI scanner)",
    durationWeeks: 1,
    locationType: "in_person",
    city: "Chapel Hill",
    state: "NC",
    facilityAddress: "Biomedical Research Imaging Center, Chapel Hill, NC 27599",
    summary: "Investigating how neural network pathways synchronize during complex working-memory tasks. Receive $400 for a single non-invasive 3T fMRI scan session.",
    fullDescription: "Participants lie comfortably in our ultra-high-resolution 3-Tesla MRI scanner while performing engaging visual memory games with an MRI-compatible mirror and response button box. Completely non-invasive with zero radiation exposure.",
    irbApprovalNumber: "UNC-IRB-26-0931",
    targetEnrollment: 50,
    currentEnrolled: 21,
    minAge: 21,
    maxAge: 45,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Ferromagnetic Implants / Pacemaker", "Severe Claustrophobia", "Tattoos with Metal Pigment"],
    targetDemographicFocus: "Young adults, students, and professionals in the Research Triangle.",
    isFeatured: false,
    isSponsored: false,
    status: "recruiting",
    createdAt: new Date("2026-08-20"),
    updatedAt: new Date("2026-09-01"),
  },
];

export const DEMO_SCREENER_QUESTIONS: Record<number, ScreenerQuestion[]> = {
  1: [
    {
      id: 101,
      studyId: 1,
      orderIndex: 1,
      questionText: "Are you between the ages of 50 and 85?",
      explanation: "Protocol is strictly designed for adults aged 50+",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Participants must be at least 50 years of age.",
    },
    {
      id: 102,
      studyId: 1,
      orderIndex: 2,
      questionText: "Have you had a stroke or traumatic brain injury within the past 6 months?",
      explanation: "Recent acute neurological trauma can skew baseline sensory test data",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Recent neurological incidents exclude participation during acute recovery phase.",
    },
    {
      id: 103,
      studyId: 1,
      orderIndex: 3,
      questionText: "Can you attend 3 scheduled in-person morning visits in Durham, NC?",
      explanation: "Visits include timed reflex assessments in the lab",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Must be able to attend all 3 on-site visits in Durham.",
    },
  ],
  2: [
    {
      id: 201,
      studyId: 2,
      orderIndex: 1,
      questionText: "Have you taken systemic oral antibiotics within the last 30 days?",
      explanation: "Recent antibiotic therapy alters circulating lymphocyte profiles",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Antibiotic exposure within 30 days alters immune baseline.",
    },
    {
      id: 202,
      studyId: 2,
      orderIndex: 2,
      questionText: "Do you have any diagnosed blood clotting or bleeding disorders?",
      explanation: "Safety requirement for routine venous phlebotomy",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Bleeding disorders present phlebotomy contraindications.",
    },
  ],
  3: [
    {
      id: 301,
      studyId: 3,
      orderIndex: 1,
      questionText: "Do you have an active smartphone capable of syncing Bluetooth data daily?",
      explanation: "The companion app requires daily sync with the study ring",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Requires compatible modern smartphone for sensor synchronization.",
    },
    {
      id: 302,
      studyId: 3,
      orderIndex: 2,
      questionText: "Do you work night shifts (between 11 PM and 6 AM) on a rotating schedule?",
      explanation: "Rotating shift work disrupts circadian baselines being benchmarked",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Study examines standard diurnal day/night sleep cycles.",
    },
  ],
  4: [
    {
      id: 401,
      studyId: 4,
      orderIndex: 1,
      questionText: "Have you been diagnosed with Type 2 Diabetes or prediabetes?",
      explanation: "Study evaluates novel glucose control in diabetic adults",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Requires diagnosed Type 2 Diabetes or documented insulin resistance.",
    },
    {
      id: 402,
      studyId: 4,
      orderIndex: 2,
      questionText: "Are you diagnosed with Type 1 Diabetes (insulin-dependent since childhood)?",
      explanation: "Protocol is strictly for Type 2 pathophysiology",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Type 1 Diabetes is an absolute protocol exclusion.",
    },
  ],
  5: [
    {
      id: 501,
      studyId: 5,
      orderIndex: 1,
      questionText: "Do you have any metallic implants, surgical clips, or pacemakers?",
      explanation: "3-Tesla magnetic field safety contraindication",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Ferromagnetic metal implants are incompatible with 3T MRI scanners.",
    },
    {
      id: 502,
      studyId: 5,
      orderIndex: 2,
      questionText: "Do you suffer from severe claustrophobia in enclosed spaces?",
      explanation: "MRI bore is an enclosed cylindrical chamber",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Participants must be comfortable lying still in the MRI scanner.",
    },
  ],
};
