import { 
  Study, 
  ScreenerQuestion, 
  ParticipantProfile,
  StudyApplication,
  ApplicationStatusHistory,
  ParticipantTask,
  ParticipantConsent,
  Notification,
  Organization,
  OrganizationMember
} from "../drizzle/schema";

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: 1,
    slug: "triangle-research-network",
    name: "Triangle Research Network",
    type: "university",
    isVerified: true,
    irbRegistrationNumber: "IRB00001842",
    contactEmail: "trials@triangleresearch.org",
    createdAt: new Date("2026-01-15"),
  },
  {
    id: 2,
    slug: "apex-pharma",
    name: "Apex Pharma Therapeutics",
    type: "pharma",
    isVerified: true,
    irbRegistrationNumber: "WIRB-98402",
    contactEmail: "clinical-ops@apexpharma.com",
    createdAt: new Date("2026-02-01"),
  },
];

export const DEMO_ORGANIZATION_MEMBERS: OrganizationMember[] = [
  {
    id: 1,
    organizationId: 1,
    userId: 201, // Dr. Whitman
    role: "study_manager",
    assignedStudySlugs: ["healthy-aging-sensory-resilience-study"],
    createdAt: new Date("2026-01-20"),
  },
  {
    id: 2,
    organizationId: 1,
    userId: 203, // Sarah Lindquist, CRC
    role: "coordinator",
    assignedStudySlugs: ["all"],
    createdAt: new Date("2026-02-10"),
  },
  {
    id: 3,
    organizationId: 2,
    userId: 204, // Dr. Elena Vance
    role: "organization_owner",
    assignedStudySlugs: ["all"],
    createdAt: new Date("2026-02-15"),
  },
];

export const DEMO_STUDIES: Study[] = [
  {
    id: 1,
    slug: "healthy-aging-sensory-resilience-study",
    title: "Healthy Aging & Multi-Sensory Neural Resilience Study",
    sponsorName: "Triangle Aging & Brain Sciences Center",
    sponsorType: "university",
    organizationId: 1,
    piName: "Dr. H. Whitman, MD",
    piTitle: "Professor of Medicine & Director, Triangle Center for Aging",
    studyType: "cognitive_assessment",
    compensationAmount: 650,
    compensationType: "Direct Deposit / Visa Gift Card",
    compensationSchedule: "$150 per visit (3 visits) + $200 completion bonus upon exit interview",
    timeCommitment: "3 visits over 6 weeks (1.5 hrs/visit)",
    durationWeeks: 6,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Triangle Clinical Research Pavilion, Durham, NC 27710",
    summary: "Investigating how combined visual and hearing cues affect cognitive resilience in older adults. Seeking healthy volunteers, especially men and rural participants.",
    fullDescription: "Our goal is to understand how the brain adapts to subtle sensory variations as we grow older. Participants undergo safe, non-invasive sensory tests and brief memory problem-solving activities on a tablet. You are compensated for each visit attended with full travel mileage reimbursements.",
    irbApprovalNumber: "Pro00109482",
    targetEnrollment: 120,
    currentEnrolled: 54,
    minAge: 50,
    maxAge: 85,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Severe Dementia", "Active Stroke within 6 months"],
    targetDemographicFocus: "Actively seeking rural residents, non-college educated volunteers, and men to achieve representative 40% male enrollment target.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 2,
    slug: "healthy-volunteer-immunology-blood-profile",
    title: "Healthy Volunteer Longitudinal Blood & Immune Profiling",
    sponsorName: "Triangle Thoracic & Surgical Immunology Lab",
    sponsorType: "hospital",
    organizationId: 1,
    piName: "Dr. Rachel Aris, MD, PhD",
    piTitle: "Chief of Cellular Immunology",
    studyType: "blood_draw",
    compensationAmount: 250,
    compensationType: "Direct Bank Deposit",
    compensationSchedule: "$100 for Visit 1 + $150 for Visit 2 (completed within 14 days)",
    timeCommitment: "2 visits (45 mins each, 2 weeks apart)",
    durationWeeks: 2,
    locationType: "in_person",
    city: "Durham",
    state: "NC",
    facilityAddress: "Hospital South Clinics, Phlebotomy Core 3B, Durham, NC 27705",
    summary: "Routine fasting blood draws two weeks apart to establish baseline lymphocyte reference data for surgical organ transplant science.",
    fullDescription: "Healthy volunteers provide approximately 35ml of venous blood across two scheduled mornings. Blood samples help researchers measure natural lymphocyte population fluctuations to build control datasets for heart and kidney transplant rejection monitors.",
    irbApprovalNumber: "IRB-2026-00412",
    targetEnrollment: 60,
    currentEnrolled: 38,
    minAge: 18,
    maxAge: 70,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Active Chronic Infection", "Immunosuppressant Medication", "Bleeding Disorder"],
    targetDemographicFocus: "Reliable healthy volunteers who can commit to two punctually scheduled morning appointments.",
    isFeatured: true,
    isSponsored: false,
    status: "recruiting",
    createdAt: new Date("2026-08-05"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 3,
    slug: "remote-sleep-cardiac-rhythm-digital-study",
    title: "National Digital Sleep & Circadian Rhythm Observational Study",
    sponsorName: "BioVanguard Digital Health Institute",
    sponsorType: "biotech",
    organizationId: 1,
    piName: "Dr. Elena Rostova, PhD",
    piTitle: "Head of Computational Chronobiology",
    studyType: "observational_survey",
    compensationAmount: 320,
    compensationType: "Amazon E-Gift Card or Venmo",
    compensationSchedule: "$80 every 2 weeks + smart ring provided free to keep upon completion",
    timeCommitment: "10 minutes daily app check-in + sleep ring wear for 6 weeks",
    durationWeeks: 6,
    locationType: "remote",
    city: "Nationwide (Remote)",
    state: "US",
    facilityAddress: "Fully remote. Devices mailed directly to your home.",
    summary: "Participate entirely from home! Receive a complimentary medical-grade smart health ring, track your sleep cycles, and log daily energy ratings via our participant mobile app.",
    fullDescription: "Explore how daily screen exposure, ambient light, and stress affect sleep micro-architecture. You will wear an unobtrusive finger sensor while sleeping and fill out a quick 2-minute morning log. No clinic visits or blood draws required. Open to adults across all 50 states.",
    irbApprovalNumber: "WIRB-2026-9921",
    targetEnrollment: 400,
    currentEnrolled: 285,
    minAge: 18,
    maxAge: 75,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Shift Work Sleep Disorder", "Untreated Severe Sleep Apnea"],
    targetDemographicFocus: "Everyday working adults, parents, and students looking for low-friction remote compensation.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-10"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 4,
    slug: "oral-glp1-cardiometabolic-phase2",
    title: "Phase II Once-Weekly Oral GLP-1 Receptor Agonist for Metabolic Health",
    sponsorName: "AstraApex Therapeutics & Triangle Endocrine Core",
    sponsorType: "pharma",
    organizationId: 2,
    piName: "Dr. Marcus Vance, MD",
    piTitle: "Principal Investigator & Chair of Metabolic Endocrinology",
    studyType: "clinical_trial",
    compensationAmount: 1850,
    compensationType: "Prepaid ClinCard / Direct Deposit",
    compensationSchedule: "$250 after screening/baseline + $200 per monthly follow-up + $450 final visit",
    timeCommitment: "8 clinic visits over 24 weeks + weekly home capsule regimen",
    durationWeeks: 24,
    locationType: "in_person",
    city: "Raleigh",
    state: "NC",
    facilityAddress: "AstraApex Phase II Clinical Trials Unit, Raleigh, NC 27607",
    summary: "Evaluating the efficacy and gastrointestinal tolerability of a novel once-weekly oral capsule formulation in individuals with elevated HbA1c or Type 2 Diabetes.",
    fullDescription: "Currently available GLP-1 therapies frequently require subcutaneous injections. This study evaluates an advanced once-weekly oral enteric capsule designed to improve metabolic glycemic control and weight parameters without injections. All medication, physician visits, and metabolic labs provided at no cost.",
    irbApprovalNumber: "IND-159483-IRB",
    targetEnrollment: 90,
    currentEnrolled: 47,
    minAge: 25,
    maxAge: 72,
    targetGender: "all",
    healthyVolunteersAccepted: false,
    requiredConditions: ["Type 2 Diabetes", "Prediabetes", "Metabolic Syndrome"],
    excludedConditions: ["Type 1 Diabetes", "History of Pancreatitis", "Thyroid C-Cell Carcinoma"],
    targetDemographicFocus: "Participants with diagnosed Type 2 Diabetes seeking novel oral therapeutic options.",
    isFeatured: true,
    isSponsored: true,
    status: "recruiting",
    createdAt: new Date("2026-08-15"),
    updatedAt: new Date("2026-09-01"),
  },
  {
    id: 5,
    slug: "mri-functional-connectome-memory-mapping",
    title: "fMRI Functional Connectome & Working Memory Precision Mapping",
    sponsorName: "Carolina Institute for Advanced Neuroimaging",
    sponsorType: "research_center",
    organizationId: 1,
    piName: "Dr. Sophia Sterling, PhD",
    piTitle: "Associate Professor of Radiology and Biomedical Imaging",
    studyType: "imaging_mri",
    compensationAmount: 400,
    compensationType: "Direct Bank Transfer or Visa Debit",
    compensationSchedule: "$400 lump sum upon completion of the 2.5-hour imaging session",
    timeCommitment: "Single 2.5-hour session (1 hour in 3T MRI scanner)",
    durationWeeks: 1,
    locationType: "in_person",
    city: "Chapel Hill",
    state: "NC",
    facilityAddress: "Biomedical Research Imaging Center, Chapel Hill, NC 27599",
    summary: "Investigating how neural network pathways synchronize during complex working-memory tasks. Receive $400 for a single non-invasive 3T fMRI scan session.",
    fullDescription: "Participants lie comfortably in our ultra-high-resolution 3-Tesla MRI scanner while performing engaging visual memory games with an MRI-compatible mirror and response button box. Completely non-invasive with zero radiation exposure.",
    irbApprovalNumber: "UNC-IRB-26-0931",
    targetEnrollment: 50,
    currentEnrolled: 21,
    minAge: 21,
    maxAge: 45,
    targetGender: "all",
    healthyVolunteersAccepted: true,
    requiredConditions: [],
    excludedConditions: ["Ferromagnetic Implants / Pacemaker", "Severe Claustrophobia", "Tattoos with Metal Pigment"],
    targetDemographicFocus: "Young adults, students, and professionals in the Research Triangle.",
    isFeatured: false,
    isSponsored: false,
    status: "recruiting",
    createdAt: new Date("2026-08-20"),
    updatedAt: new Date("2026-09-01"),
  },
];


export const DEMO_SCREENER_QUESTIONS: Record<number, ScreenerQuestion[]> = {
  1: [
    {
      id: 101,
      studyId: 1,
      orderIndex: 1,
      questionText: "Are you between the ages of 50 and 85?",
      explanation: "Protocol is strictly designed for adults aged 50+",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Participants must be at least 50 years of age.",
    },
    {
      id: 102,
      studyId: 1,
      orderIndex: 2,
      questionText: "Have you had a stroke or traumatic brain injury within the past 6 months?",
      explanation: "Recent acute neurological trauma can skew baseline sensory test data",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Recent neurological incidents exclude participation during acute recovery phase.",
    },
    {
      id: 103,
      studyId: 1,
      orderIndex: 3,
      questionText: "Can you attend 3 scheduled in-person morning visits in Durham, NC?",
      explanation: "Visits include timed reflex assessments in the lab",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Must be able to attend all 3 on-site visits in Durham.",
    },
  ],
  2: [
    {
      id: 201,
      studyId: 2,
      orderIndex: 1,
      questionText: "Have you taken systemic oral antibiotics within the last 30 days?",
      explanation: "Recent antibiotic therapy alters circulating lymphocyte profiles",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Antibiotic exposure within 30 days alters immune baseline.",
    },
    {
      id: 202,
      studyId: 2,
      orderIndex: 2,
      questionText: "Do you have any diagnosed blood clotting or bleeding disorders?",
      explanation: "Safety requirement for routine venous phlebotomy",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Bleeding disorders present phlebotomy contraindications.",
    },
  ],
  3: [
    {
      id: 301,
      studyId: 3,
      orderIndex: 1,
      questionText: "Do you have an active smartphone capable of syncing Bluetooth data daily?",
      explanation: "The companion app requires daily sync with the study ring",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Requires compatible modern smartphone for sensor synchronization.",
    },
    {
      id: 302,
      studyId: 3,
      orderIndex: 2,
      questionText: "Do you work night shifts (between 11 PM and 6 AM) on a rotating schedule?",
      explanation: "Rotating shift work disrupts circadian baselines being benchmarked",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Study examines standard diurnal day/night sleep cycles.",
    },
  ],
  4: [
    {
      id: 401,
      studyId: 4,
      orderIndex: 1,
      questionText: "Have you been diagnosed with Type 2 Diabetes or prediabetes?",
      explanation: "Study evaluates novel glucose control in diabetic adults",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "yes",
      isDisqualifying: true,
      disqualificationReason: "Requires diagnosed Type 2 Diabetes or documented insulin resistance.",
    },
    {
      id: 402,
      studyId: 4,
      orderIndex: 2,
      questionText: "Are you diagnosed with Type 1 Diabetes (insulin-dependent since childhood)?",
      explanation: "Protocol is strictly for Type 2 pathophysiology",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Type 1 Diabetes is an absolute protocol exclusion.",
    },
  ],
  5: [
    {
      id: 501,
      studyId: 5,
      orderIndex: 1,
      questionText: "Do you have any metallic implants, surgical clips, or pacemakers?",
      explanation: "3-Tesla magnetic field safety contraindication",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Ferromagnetic metal implants are incompatible with 3T MRI scanners.",
    },
    {
      id: 502,
      studyId: 5,
      orderIndex: 2,
      questionText: "Do you suffer from severe claustrophobia in enclosed spaces?",
      explanation: "MRI bore is an enclosed cylindrical chamber",
      questionType: "yes_no",
      options: ["yes", "no"],
      expectedAnswer: "no",
      isDisqualifying: true,
      disqualificationReason: "Participants must be comfortable lying still in the MRI scanner.",
    },
  ],
};

/* ==================== DEMO PARTICIPANT PROFILES ==================== */
export const DEMO_PARTICIPANT_PROFILES: ParticipantProfile[] = [
  {
    id: 1,
    userId: 101, // Marcus Davis
    profileKey: "demo_profile_rural_male",
    fullName: "Marcus Davis",
    email: "marcus.davis92@example.com",
    phone: "919-555-0144",
    age: 58,
    gender: "male",
    educationLevel: "high_school_or_less",
    livingEnvironment: "rural",
    city: "Sanford",
    state: "NC",
    zipCode: "27330",
    travelDistanceMiles: 45,
    isHealthyVolunteer: true,
    conditions: [],
    medications: [],
    hasRecentAntibiotics: false,
    smokerStatus: "never",
    preferredContactMethod: "phone",
    isContactVerified: true,
    preferredLocationType: "in_person",
    preferredLanguage: "English",
    transportationAccess: "personal_vehicle",
    accessibilityNeeds: null,
    hasCaregiver: false,
    hasInternetSmartphone: true,
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-09-10"),
  },
  {
    id: 2,
    userId: 103, // Chloe Martinez
    profileKey: "prof_chloe_student",
    fullName: "Chloe Martinez",
    email: "chloe.m.student@example.edu",
    phone: "919-555-0189",
    age: 23,
    gender: "female",
    educationLevel: "bachelors",
    livingEnvironment: "urban",
    city: "Durham",
    state: "NC",
    zipCode: "27708",
    travelDistanceMiles: 15,
    isHealthyVolunteer: true,
    conditions: [],
    medications: [],
    hasRecentAntibiotics: false,
    smokerStatus: "never",
    preferredContactMethod: "email",
    isContactVerified: true,
    preferredLocationType: "hybrid",
    preferredLanguage: "English",
    transportationAccess: "public_transit",
    accessibilityNeeds: null,
    hasCaregiver: false,
    hasInternetSmartphone: true,
    createdAt: new Date("2026-08-05"),
    updatedAt: new Date("2026-09-08"),
  },
  {
    id: 3,
    userId: 104, // Robert Chen
    profileKey: "prof_robert_patient",
    fullName: "Robert Chen",
    email: "robert.chen.t2d@example.org",
    phone: "919-555-0199",
    age: 52,
    gender: "male",
    educationLevel: "graduate_degree",
    livingEnvironment: "suburban",
    city: "Cary",
    state: "NC",
    zipCode: "27519",
    travelDistanceMiles: 25,
    isHealthyVolunteer: false,
    conditions: ["Type 2 Diabetes", "Prediabetes"],
    medications: ["Metformin"],
    hasRecentAntibiotics: false,
    smokerStatus: "never",
    preferredContactMethod: "email",
    isContactVerified: true,
    preferredLocationType: "in_person",
    preferredLanguage: "English",
    transportationAccess: "personal_vehicle",
    accessibilityNeeds: null,
    hasCaregiver: false,
    hasInternetSmartphone: true,
    createdAt: new Date("2026-08-10"),
    updatedAt: new Date("2026-09-09"),
  },
];

/* ==================== DEMO APPLICATIONS & LIFECYCLE STAGES ==================== */
export const DEMO_APPLICATIONS: StudyApplication[] = [
  // Marcus Davis on Study 1 (Sensory resilience) -> action_needed
  {
    id: 1,
    studyId: 1,
    profileId: 1,
    status: "action_needed",
    screenerResponses: { "101": "yes", "102": "no", "103": "yes" },
    qualificationScore: 100,
    disqualificationNotes: null,
    researcherNotes: "High priority rural male participant. Phone screen verified.",
    participantFacingNote: "Please confirm your availability for the baseline sensory intake session with Coordinator Sarah.",
    internalStaffNote: "Eligible for 40% male balancing quota. Travel stipend calculated for Sanford, NC.",
    assignedCoordinatorId: 203,
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: new Date("2026-09-14T10:30:00Z"),
    lastStatusChangedByUserId: 203,
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: new Date("2026-09-24T13:00:00Z"),
    createdAt: new Date("2026-09-02T14:22:00Z"),
    updatedAt: new Date("2026-09-14T10:30:00Z"),
  },
  // Marcus Davis on Study 2 (Immunology blood profile) -> enrolled
  {
    id: 2,
    studyId: 2,
    profileId: 1,
    status: "enrolled",
    screenerResponses: { "201": "no", "202": "no" },
    qualificationScore: 100,
    disqualificationNotes: null,
    researcherNotes: "Visit 1 phlebotomy complete. Specimen processed.",
    participantFacingNote: "Enrolled in Phase A. Visit 1 completed on Sept 10. Visit 2 scheduled for Sept 24.",
    internalStaffNote: "Consent signed on file. Blood draw tubes 1-3 stored at -80C core freezer.",
    assignedCoordinatorId: 203,
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: new Date("2026-09-10T11:00:00Z"),
    lastStatusChangedByUserId: 201,
    lastStatusChangedByName: "Dr. H. Whitman, MD",
    appointmentDate: new Date("2026-09-24T09:00:00Z"),
    createdAt: new Date("2026-08-28T09:15:00Z"),
    updatedAt: new Date("2026-09-10T11:00:00Z"),
  },
  // Marcus Davis on Study 3 (Sleep Observational) -> under_review
  {
    id: 3,
    studyId: 3,
    profileId: 1,
    status: "under_review",
    screenerResponses: { "301": "yes", "302": "no" },
    qualificationScore: 100,
    disqualificationNotes: null,
    researcherNotes: "Hardware dispatch queue pending sensor batch allocation.",
    participantFacingNote: "Application submitted. The digital research team is preparing your smart ring sensor kit for shipping.",
    internalStaffNote: "Mailing address validated with USPS core API.",
    assignedCoordinatorId: 203,
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: new Date("2026-09-12T15:00:00Z"),
    lastStatusChangedByUserId: 203,
    lastStatusChangedByName: "Sarah Lindquist, CRC",
    appointmentDate: null,
    createdAt: new Date("2026-09-05T18:40:00Z"),
    updatedAt: new Date("2026-09-12T15:00:00Z"),
  },
  // Marcus Davis on Study 4 (Oral GLP-1) -> not_selected (with respectful guidance)
  {
    id: 4,
    studyId: 4,
    profileId: 1,
    status: "not_selected",
    screenerResponses: { "401": "no", "402": "no" },
    qualificationScore: 40,
    disqualificationNotes: "Requires diagnosed Type 2 Diabetes or documented metabolic syndrome.",
    researcherNotes: "Healthy volunteer applied to condition-specific trial.",
    participantFacingNote: "Thank you for your application. Because this study requires a diagnosed metabolic condition (Type 2 Diabetes), your profile was not selected for this protocol. Please explore our alternative healthy volunteer studies below.",
    internalStaffNote: "Respectful decline sent with recommendations.",
    assignedCoordinatorId: null,
    assignedCoordinatorName: null,
    statusUpdatedAt: new Date("2026-09-08T09:20:00Z"),
    lastStatusChangedByUserId: 204,
    lastStatusChangedByName: "Dr. Elena Vance, MD",
    appointmentDate: null,
    createdAt: new Date("2026-09-06T11:30:00Z"),
    updatedAt: new Date("2026-09-08T09:20:00Z"),
  },
  // Chloe Martinez on Study 5 (fMRI Brain Mapping) -> eligible_next_step
  {
    id: 5,
    studyId: 5,
    profileId: 2,
    status: "eligible_next_step",
    screenerResponses: { "501": "no", "502": "no" },
    qualificationScore: 100,
    disqualificationNotes: null,
    researcherNotes: "Zero metal contraindications. Prime student participant for memory protocol.",
    participantFacingNote: "Pre-screen verified! You are eligible to book your 2.5-hour fMRI scan session at Chapel Hill.",
    internalStaffNote: "Safety clearance signed off by Dr. Sterling.",
    assignedCoordinatorId: 203,
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: new Date("2026-09-15T14:10:00Z"),
    lastStatusChangedByUserId: 201,
    lastStatusChangedByName: "Dr. H. Whitman, MD",
    appointmentDate: new Date("2026-09-26T14:00:00Z"),
    createdAt: new Date("2026-09-04T12:00:00Z"),
    updatedAt: new Date("2026-09-15T14:10:00Z"),
  },
  // Robert Chen on Study 4 (Oral GLP-1) -> enrolled
  {
    id: 6,
    studyId: 4,
    profileId: 3,
    status: "enrolled",
    screenerResponses: { "401": "yes", "402": "no" },
    qualificationScore: 100,
    disqualificationNotes: null,
    researcherNotes: "Baseline HbA1c 7.9% verified. Study drug kit #104 dispensed.",
    participantFacingNote: "Active participant in Phase II Oral GLP-1 Trial. Next clinic follow-up scheduled for October 4.",
    internalStaffNote: "Informed consent v3 signed. Fasting lipids and glucose normal at baseline.",
    assignedCoordinatorId: 203,
    assignedCoordinatorName: "Sarah Lindquist, CRC",
    statusUpdatedAt: new Date("2026-09-11T16:00:00Z"),
    lastStatusChangedByUserId: 204,
    lastStatusChangedByName: "Dr. Elena Vance, MD",
    appointmentDate: new Date("2026-10-04T10:00:00Z"),
    createdAt: new Date("2026-08-30T10:15:00Z"),
    updatedAt: new Date("2026-09-11T16:00:00Z"),
  },
];

/* ==================== DEMO APPLICATION STATUS HISTORY ==================== */
export const DEMO_STATUS_HISTORY: ApplicationStatusHistory[] = [
  {
    id: 1,
    applicationId: 1,
    fromStatus: "submitted",
    toStatus: "under_review",
    changedByUserId: 203,
    changedByName: "Sarah Lindquist, CRC",
    participantFacingNote: "Application received and under clinical review.",
    internalNote: "Rural male profile flagged for representation target.",
    createdAt: new Date("2026-09-03T11:00:00Z"),
  },
  {
    id: 2,
    applicationId: 1,
    fromStatus: "under_review",
    toStatus: "action_needed",
    changedByUserId: 203,
    changedByName: "Sarah Lindquist, CRC",
    participantFacingNote: "Please confirm your availability for the baseline sensory intake session with Coordinator Sarah.",
    internalNote: "Coordinator outreach attempted via phone. Left voicemail.",
    createdAt: new Date("2026-09-14T10:30:00Z"),
  },
  {
    id: 3,
    applicationId: 2,
    fromStatus: "submitted",
    toStatus: "eligible_next_step",
    changedByUserId: 203,
    changedByName: "Sarah Lindquist, CRC",
    participantFacingNote: "Screener passed. Ready for initial phlebotomy visit.",
    internalNote: "Lab slot confirmed.",
    createdAt: new Date("2026-09-01T10:00:00Z"),
  },
  {
    id: 4,
    applicationId: 2,
    fromStatus: "eligible_next_step",
    toStatus: "enrolled",
    changedByUserId: 201,
    changedByName: "Dr. H. Whitman, MD",
    participantFacingNote: "Enrolled in Phase A. Visit 1 completed on Sept 10. Visit 2 scheduled for Sept 24.",
    internalNote: "Participant signed consent and completed first blood draw.",
    createdAt: new Date("2026-09-10T11:00:00Z"),
  },
  {
    id: 5,
    applicationId: 4,
    fromStatus: "submitted",
    toStatus: "not_selected",
    changedByUserId: 204,
    changedByName: "Dr. Elena Vance, MD",
    participantFacingNote: "Thank you for your application. Because this study requires a diagnosed metabolic condition (Type 2 Diabetes), your profile was not selected for this protocol.",
    internalNote: "Protocol inclusion requires documented T2D diagnosis. Disqualified gently.",
    createdAt: new Date("2026-09-08T09:20:00Z"),
  },
];

/* ==================== DEMO PARTICIPANT TASKS ==================== */
export const DEMO_TASKS: ParticipantTask[] = [
  {
    id: 1,
    applicationId: 1,
    profileKey: "demo_profile_rural_male",
    taskType: "confirm_availability",
    title: "Confirm Availability for Baseline Sensory Intake",
    description: "Coordinator Sarah Lindquist is scheduling your 90-minute initial sensory intake visit in Durham. Please select your preferred day and time.",
    status: "pending",
    actionUrl: "/study/healthy-aging-sensory-resilience-study",
    dueDate: new Date("2026-09-22T23:59:59Z"),
    completedAt: null,
    createdById: 203,
    createdByName: "Sarah Lindquist, CRC",
    createdAt: new Date("2026-09-14T10:30:00Z"),
  },
  {
    id: 2,
    applicationId: 1,
    profileKey: "demo_profile_rural_male",
    taskType: "confirm_contact",
    title: "Confirm Preferred Phone Number for Coordinator Callback",
    description: "Verify that (919) 555-0144 is the best phone number for Coordinator Sarah to reach you.",
    status: "completed",
    actionUrl: "/profile",
    dueDate: new Date("2026-09-15T23:59:59Z"),
    completedAt: new Date("2026-09-14T12:15:00Z"),
    createdById: 203,
    createdByName: "Sarah Lindquist, CRC",
    createdAt: new Date("2026-09-12T09:00:00Z"),
  },
  {
    id: 3,
    applicationId: 3,
    profileKey: "demo_profile_rural_male",
    taskType: "review_study_details",
    title: "Review Digital Sleep Ring Setup Guide",
    description: "Familiarize yourself with how the smart sleep ring syncs via Bluetooth before hardware arrival.",
    status: "pending",
    actionUrl: "/study/remote-sleep-cardiac-rhythm-digital-study",
    dueDate: new Date("2026-09-25T23:59:59Z"),
    completedAt: null,
    createdById: 203,
    createdByName: "Sarah Lindquist, CRC",
    createdAt: new Date("2026-09-13T14:00:00Z"),
  },
];

/* ==================== DEMO PARTICIPANT CONSENTS ==================== */
export const DEMO_CONSENTS: ParticipantConsent[] = [
  {
    id: 1,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "terms_of_service",
    version: "2026.1",
    isGranted: true,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: null,
  },
  {
    id: 2,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "privacy_policy",
    version: "2026.1",
    isGranted: true,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: null,
  },
  {
    id: 3,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "matching_communications",
    version: "2026.1",
    isGranted: true,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: null,
  },
  {
    id: 4,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "transactional_email",
    version: "2026.1",
    isGranted: true,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: null,
  },
  {
    id: 5,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "marketing_email",
    version: "2026.1",
    isGranted: false,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: new Date("2026-08-01T10:00:00Z"),
  },
  {
    id: 6,
    profileKey: "demo_profile_rural_male",
    userId: 101,
    consentType: "sms_opt_in",
    version: "2026.1",
    isGranted: false,
    ipAddress: "127.0.0.1",
    grantedAt: new Date("2026-08-01T10:00:00Z"),
    revokedAt: null,
  },
];

/* ==================== DEMO NOTIFICATIONS ==================== */
export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    userId: 101,
    profileKey: "demo_profile_rural_male",
    eventType: "action_required",
    title: "Action Required: Baseline Sensory Intake",
    body: "Coordinator Sarah Lindquist requested availability for your first visit on the Healthy Aging study.",
    actionUrl: "/my-studies",
    studyId: 1,
    applicationId: 1,
    taskId: 1,
    isRead: false,
    emailAttempted: true,
    emailDelivered: true,
    emailRecipient: "marcus.davis92@example.com",
    emailDeliveryLog: "[Simulated Delivery] SMTP Status 250 OK - Sent to marcus.davis92@example.com",
    createdAt: new Date("2026-09-14T10:30:00Z"),
  },
  {
    id: 2,
    userId: 101,
    profileKey: "demo_profile_rural_male",
    eventType: "status_changed",
    title: "Enrolled: Blood Profile Study",
    body: "Congratulations, your enrollment in Phase A of the Longitudinal Blood Profiling study is confirmed.",
    actionUrl: "/my-studies",
    studyId: 2,
    applicationId: 2,
    taskId: null,
    isRead: true,
    emailAttempted: true,
    emailDelivered: true,
    emailRecipient: "marcus.davis92@example.com",
    emailDeliveryLog: "[Simulated Delivery] SMTP Status 250 OK - Sent to marcus.davis92@example.com",
    createdAt: new Date("2026-09-10T11:00:00Z"),
  },
  {
    id: 3,
    userId: 101,
    profileKey: "demo_profile_rural_male",
    eventType: "application_submitted",
    title: "Application Received: Digital Sleep Study",
    body: "Your pre-screener was received by BioVanguard Digital Health Institute.",
    actionUrl: "/my-studies",
    studyId: 3,
    applicationId: 3,
    taskId: null,
    isRead: true,
    emailAttempted: true,
    emailDelivered: true,
    emailRecipient: "marcus.davis92@example.com",
    emailDeliveryLog: "[Simulated Delivery] SMTP Status 250 OK - Sent to marcus.davis92@example.com",
    createdAt: new Date("2026-09-05T18:40:00Z"),
  },
];
